# -*- coding: utf-8 -*-
"""Extracting_10_Frames.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f7ggaP033NvjdiMjgUV6mrB1jDdBKtjL
"""

import os
import cv2

def organize_frames(video_dir, output_dir, max_frames_per_video=10, frame_rate=1):
    os.makedirs(output_dir, exist_ok=True)

    for label in os.listdir(video_dir):
        label_dir = os.path.join(video_dir, label)
        if os.path.isdir(label_dir):
            for video_filename in os.listdir(label_dir):
                if video_filename.endswith(".mp4"):
                    video_name = os.path.splitext(video_filename)[0]
                    video_path = os.path.join(label_dir, video_filename)
                    frame_dir = os.path.join(output_dir, label, video_name)
                    print(f"Extracting frames from {video_path} to {frame_dir}")
                    extract_frames(video_path, frame_dir, max_frames_per_video, frame_rate)

def extract_frames(video_path, output_dir, max_frames_per_video, frame_rate):
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print(f"Error: Could not open video {video_path}.")
        return

    os.makedirs(output_dir, exist_ok=True)

    frame_count = 0
    frame_index = 0

    while frame_index < max_frames_per_video:
        ret, frame = cap.read()

        if not ret:
            break

        if frame_count % int(cap.get(cv2.CAP_PROP_FPS) / frame_rate) == 0:
            frame_filename = f"{frame_index:04d}.jpg"
            frame_path = os.path.join(output_dir, frame_filename)
            cv2.imwrite(frame_path, frame)
            print(f"Saved frame {frame_index}")
            frame_index += 1

        frame_count += 1

    cap.release()


video_dir = "/content/drive/MyDrive/Dataset/Train"
output_dir = "/content/drive/MyDrive/Train_Frames"
organize_frames(video_dir, output_dir, max_frames_per_video=10, frame_rate=1)